const data = {
    products: [
        {
            name: 'Nike Slim shirt',
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: '/img/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Adidas Slim shirt',
            slug: 'Adidas-slim-shirt',
            category: 'Shirts',
            image: '/img/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 8,
            description: 'high quality shirt',
        },
        {
            name: 'Reebook Slim shirt',
            slug: 'Reebook-slim-shirt',
            category: 'Shirts',
            image: '/img/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Reebook',
            rating: 4.5,
            numReviews: 5,
            description: 'high quality shirt',
        },
        {
            name: 'Vans Slim shirt',
            slug: 'Vans-slim-shirt',
            category: 'Shirts',
            image: '/img/p4.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Vans',
            rating: 4.5,
            numReviews: 6,
            description: 'high quality shirt',
        },
    ],
};

export default data